/**
 * Identifiers (ADR-004).
 *
 * - Row IDs: UUIDv7 — time-ordered, generated on-device, no coordination, no collisions.
 * - Op IDs: ULID — lexicographically sortable, used as sync cursors/dedupe keys.
 *
 * Randomness comes from an injectable RandomPort (WebCrypto by default, which exists
 * in Node 22, browsers, and React Native runtimes).
 */

export interface RandomPort {
  bytes(n: number): Uint8Array;
}

class WebCryptoRandom implements RandomPort {
  bytes(n: number): Uint8Array {
    return globalThis.crypto.getRandomValues(new Uint8Array(n));
  }
}

export const defaultRandom: RandomPort = new WebCryptoRandom();

const HEX = '0123456789abcdef';

function toHex(bytes: Uint8Array): string {
  let out = '';
  for (const b of bytes) {
    out += HEX[(b >> 4) & 0xf]!;
    out += HEX[b & 0xf]!;
  }
  return out;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

/** Generate a UUIDv7 (48-bit unix ms + version/variant + 74 random bits). */
export function uuidv7(rand: RandomPort = defaultRandom): string {
  const b = rand.bytes(16);
  const ts = Date.now();
  // 48-bit big-endian timestamp
  b[0] = Math.floor(ts / 2 ** 40) & 0xff;
  b[1] = Math.floor(ts / 2 ** 32) & 0xff;
  b[2] = Math.floor(ts / 2 ** 24) & 0xff;
  b[3] = Math.floor(ts / 2 ** 16) & 0xff;
  b[4] = Math.floor(ts / 2 ** 8) & 0xff;
  b[5] = ts & 0xff;
  // version 7
  b[6] = (b[6]! & 0x0f) | 0x70;
  // variant 10xx
  b[8] = (b[8]! & 0x3f) | 0x80;
  const h = toHex(b);
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}

export function isUuidv7(value: string): boolean {
  return UUID_RE.test(value);
}

/** Extract the 48-bit timestamp (ms) from a UUIDv7; null for other versions. */
export function uuidv7Timestamp(value: string): number | null {
  if (!isUuidv7(value)) return null;
  const hex = value.replace(/-/g, '').slice(0, 12);
  return parseInt(hex, 16);
}

// ---------------------------------------------------------------------------
// ULID (Crockford base32, 26 chars: 10 time chars + 16 randomness chars)
// ---------------------------------------------------------------------------

const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
const ULID_RE = /^[0-9ABCDEFGHJKMNPQRSTVWXYZ]{26}$/;

export function isUlid(value: string): boolean {
  return ULID_RE.test(value);
}

/**
 * Monotonic ULID factory: within the same millisecond, the random component is
 * incremented, so ULIDs generated by one process sort in generation order.
 */
export class UlidFactory {
  readonly #rand: RandomPort;
  #lastMs: number = -1;
  #lastRand: Uint8Array = new Uint8Array(10);

  constructor(rand: RandomPort = defaultRandom) {
    this.#rand = rand;
  }

  next(nowMs: number = Date.now()): string {
    if (nowMs === this.#lastMs) {
      this.#incrementRandom();
    } else if (nowMs > this.#lastMs) {
      this.#lastMs = nowMs;
      this.#lastRand = this.#rand.bytes(10);
    } else {
      // Clock went backwards: keep monotonicity by incrementing the last value's time.
      this.#lastMs = this.#lastMs; // time stays at the higher watermark
      this.#incrementRandom();
    }
    return UlidFactory.#encode(this.#lastMs, this.#lastRand);
  }

  #incrementRandom(): void {
    for (let i = this.#lastRand.length - 1; i >= 0; i--) {
      const v = this.#lastRand[i]! + 1;
      if (v <= 0xff) {
        this.#lastRand[i] = v;
        return;
      }
      this.#lastRand[i] = 0; // carry
    }
    // Full carry overflow (2^80 ops in one ms — unreachable in practice): re-randomize.
    this.#lastRand = this.#rand.bytes(10);
  }

  static #encode(ms: number, rand: Uint8Array): string {
    // 48-bit time -> 10 chars (MSB first)
    let t = ms;
    const timeChars: string[] = new Array<string>(10);
    for (let i = 9; i >= 0; i--) {
      timeChars[i] = CROCKFORD[t & 31]!;
      t = Math.floor(t / 32);
    }
    // 80-bit random -> 16 chars (MSB first)
    let value = 0n;
    for (const byte of rand) value = (value << 8n) | BigInt(byte);
    const randChars: string[] = new Array<string>(16);
    for (let i = 15; i >= 0; i--) {
      randChars[i] = CROCKFORD[Number(value & 31n)]!;
      value >>= 5n;
    }
    return timeChars.join('') + randChars.join('');
  }
}
