import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { api, ksh, monthName } from '../api';

const METHOD_LABEL: Record<string, string> = { MPESA: 'M-Pesa', CASH: 'Cash', BANK: 'Bank', OTHER: 'Other' };

export default function ReceiptView() {
  const { id } = useParams();
  const [r, setR] = useState<any | null>(null);
  const [err, setErr] = useState('');
  useEffect(() => { api.get(`/receipts/${id}`).then(setR).catch((e) => setErr(e.message)); }, [id]);
  if (err) return <div className="alert error">{err}</div>;
  if (!r) return null;
  const s = r.snapshot;

  return (
    <>
      <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', maxWidth: 460, margin: '0 auto 14px' }}>
        <h1 style={{ fontSize: 19 }}>Rent Receipt</h1>
        <button className="btn small" onClick={() => window.print()}>🖨 Print / Save PDF</button>
      </div>

      <div className="receipt">
        <div className="rhead">
          <div className="org">{s.orgName}</div>
          <div className="prop">{s.propertyName}{s.propertyLocation ? ` · ${s.propertyLocation}` : ''}</div>
          <div className="rno">RECEIPT {s.receiptNo}</div>
        </div>

        <dl>
          <dt>Received from</dt><dd>{s.tenantName}</dd>
          <dt>House</dt><dd>{s.unitLabel}</dd>
          <dt>Payment date</dt><dd>{s.paymentDate}</dd>
          <dt>For period</dt><dd>{monthName(s.period)}</dd>
          <dt>Method</dt><dd>{METHOD_LABEL[s.method] || s.method}</dd>
          {s.reference && (<><dt>Reference</dt><dd>{s.reference}</dd></>)}
        </dl>

        <div className="amount-row"><span>Amount paid</span><span>{ksh(s.amountMinor)}</span></div>

        <dl>
          <dt>Balance before</dt><dd>{ksh(s.previousBalanceMinor)}</dd>
          <dt>Balance after</dt><dd style={{ color: s.remainingBalanceMinor > 0 ? 'var(--amber)' : 'var(--green)' }}>{ksh(s.remainingBalanceMinor)}</dd>
        </dl>

        <div className="sig">
          <div>
            <div className="line">{s.issuedBy}</div>
            <div className="cap">Authorized signature</div>
          </div>
          <div className="cap" style={{ textAlign: 'right' }}>
            Issued {new Date(s.issuedAt).toLocaleString('en-KE', { dateStyle: 'medium', timeStyle: 'short' })}<br />by {s.issuedBy}
          </div>
        </div>

        <div className="foot">Generated by Kitabu Digital · This receipt is a permanent record and cannot be altered.</div>
      </div>
    </>
  );
}
